name: CI pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  test_job:
    name: Test the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repo
        uses: actions/checkout@v4

      - name: Setup app dependencies
        uses: ./.github/actions/setup-app-dependencies

      - name: Setup chromium
        id: setup-chromium
        uses: ./.github/actions/setup-chromium

      - name: Run npm tests for CI
        run: npm run test-ci
        env:
          CHROME_BIN: ${{ steps.setup-chromium.outputs.chrome-path }}
